### ISSUE TITLE
Change Sensitvity Settings

### ISSUE THREAD

**Issue by DanielHabenicht** [ApolloAutomation/MTR-1#23]
Hey there, 

I recently ordered a MTR-1 and it is working great.
However, it has issues with ghosting (meaning detection of people in the room without them being there). 
The [FAQ page](https://wiki.apolloautomation.com/products/mtr1/faq/) mentions that the sensitivity can be adjusted (Question 11) but I could not find any information on what can be adjusted. 

Hope you can help.

**Comment by bharvey88** [comment]
Apologies, it looks like this was copied from the MSR-2 FAQ and should be removed from the wiki. The MTR-1 is unable to tweak the sensitivity in the same way the LD2410B in the MSR-2 can.

**Comment by DanielHabenicht** [comment]
Alright, thanks for your answer. It should probably be removed then. 
Is there any other way (planned) to reduce sensitivity?

**Comment by bharvey88** [comment]
Sadly no, we use sensors made by other companies and combine them with custom PCBs- you're really asking more if the company HLK who makes the mmWave sensors we use can add functionality and we have no connection with them

We can add lots of functionality with yaml but not this sorry.

**Comment by DanielHabenicht** [comment]
Would it be possible to add zones where detections are suppressed? Similar to the zones already available, but working the other way around. 
So any detections inside them are ignored for the overall metrics.
